---
- name: Passwordless Authentication
  hosts: sriansible-srv, sriansible-client1
  remote_user: ansadmin
  become: true
  tasks:
    - name: Generating public and private keys for user ashok
      user:
        name: ashok
        generate_ssh_key: yes
        ssh_key_type: rsa
        state: present

- name: Copy public key to clients
  hosts: sriansible-srv, sriansible-client1
  remote_user: ansadmin
  become: true
  tasks:
    - name: Fetch public key from sriansible-srv
      fetch:
        src: /home/ashok/.ssh/id_rsa.pub
        dest: /tmp/id_rsa.pub
        flat: yes

    - name: Ensure .ssh directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    - name: Append public key to authorized_keys
      authorized_key:
        user: ashok
        key: "{{ lookup('file', '/tmp/id_rsa.pub') }}"
        state: present

