---
- name: user creation
  hosts: sriansible-srv, sriansible-client1
  remote_user: ansadmin
  become: true
  tasks:
        -  name: create a group
           group:
                 name: ashok
                 gid: 5200
        -  name: create a user
           user:
                name: ashok
                uid: 5300
                group: ashok
                comment: ashok@outlook.com
                state: present
        -  name: generating password for user
           user:
                name: ashok
                password: "{{ 'ashok@123' | password_hash('sha512') }}"
