---
- name: Removing A User
  hosts: appsrv, dbsrv, websrv
  remote_user: ansadmin
  become: true
  tasks:
        -  name: Removing the ashok User
           user:
                name: ashok 
                remove: yes
                state: absent
        -  name: Removing the ashok user
           group: 
                 name: ashok
                 remove: yes
                 state: absent        
      
